version: '3.8'

services:
  ai-service:
    image: ai-service:latest
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP="ai_service:create_app('config.DockerComposeConfig')"
    depends_on:
      - qdrant

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"

